name:                news
version:             0.1.0.0
github:              "githubuser/news"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/news#readme>

dependencies:
- base >= 4.7 && < 5
- configurator        # работа с конфигом
- time                # Data.Time.Calendar Data.Time для добавления текущего времени в логирование
- text                # Data.Text
- QuickCheck
- bytestring          # for use Data.ByteString.Lazy.Char8
- hspec
- servant  #Servant.API
- servant-server # http server
- postgresql-simple
- resource-pool
- memory # Data.ByteArray.Encoding
- cryptonite #Crypto.Hash
- aeson #Data.Aeson
- warp #Network.Wai.Handler.Warp (run)
- mtl # Control.Monad.Identity
- base64  # Data.ByteString.Base64 
- containers  # Data.Map 
- safe-exceptions #Control.Exception.Safe (throwString for working whith config) 
- directory
- postgresql-simple-migration  

# About ghc options read here. https://ghc.gitlab.haskell.org/ghc/doc/users_guide/using-warnings.html#
ghc-options:
- -Wall              # enable almost all warnings
- -Werror            # make warnings fatal
- -Wincomplete-uni-patterns # Warns about places where a pattern-match might fail at runtime.
- -Wcompat    # Turns on warnings that will be enabled by default in the future, 
              # but remain off in normal compilations for the time being. 
              # This allows library authors eager to make their code future compatible to adapt to new features before they even generate warnings.


library:
  source-dirs: src

executables:
  news-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - news

tests:
  news-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - news
